export const PaginationTypes = {
  NEXT_PAGE: 'NEXT_PAGE',
  PREV_PAGE: 'PREV_PAGE'
};

export const FeedbackTypes = {
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES'
};

export const DataActions = {
  REQUEST_DATA_LIST: 'REQUEST_DATA_LIST',
  RECEIVE_DATA_LIST: 'RECEIVE_DATA_LIST',
  REQUEST_DATA_ITEM: 'REQUEST_DATA_ITEM',
  RECEIVE_DATA_ITEM: 'RECEIVE_DATA_ITEM',
};
